from langchain.chains.summarize import load_summarize_chain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain_community.llms import Ollama
from backend.llms.ollama.ollama_llm import Ollamallm
from .action_items import ActionItems
from .template_refine import *

"""
Refine chain.

The refine documents chain constructs a response by iterating over the input documents
and progressively updating a rolling summary.
"""

class ActionItemsRefine(ActionItems):
    """
    A class to handle the action items using an iterative summarization process.

    This class extends the `ActionItems` class to provide a refined summarization by iterating over the input transcript 
    and updating the summary progressively. It uses a language model to generate summaries based on a rolling context.

    Attributes:
        llm (Ollamallm): The language model used for summarization and refinement.
        chain (BaseCombineDocumentsChain): The chain used for processing the documents.
    
    Methods:
        __init__(self, llm: Ollamallm, refine_prompt: str, question_prompt: str):
            Initializes the ActionItemsRefine object with a language model and prompts for refining and organizing.
        
        generate_final_follow_up(self, follow_up: str) -> str:
            Generates a follow-up prompt based on a given follow-up text and invokes the language model.
    """

    def __init__(self, llm: Ollamallm,
                 refine_prompt=ActionItemsRefinePrompts.refine_prompt_default(),
                 question_prompt=ActionItemsRefinePrompts.organize_prompt_default()):
        """
        Initializes the ActionItemsRefine object with a language model and prompts for refining and organizing.

        Args:
            llm (Ollamallm): The language model used for summarization and refinement.
            refine_prompt (str, optional): The prompt used to guide the refinement process. Defaults to `ActionItemsRefinePrompts.refine_prompt_default()`.
            question_prompt (str, optional): The prompt used for organizing the action items. Defaults to `ActionItemsRefinePrompts.organize_prompt_default()`.
        """
        ActionItems.__init__(self,
            load_summarize_chain(
                llm, 
                chain_type="refine", 
                question_prompt=question_prompt,
                refine_prompt=refine_prompt, 
                document_variable_name="text", 
                initial_response_name="existing_answer"
            )
        )
        self.llm = llm

    def generate_final_follow_up(self, follow_up):
        """
        Generates a follow-up prompt based on a given follow-up text and invokes the language model.

        Args:
            follow_up (str): The follow-up text to be incorporated into the refinement process.

        Returns:
            str: The response generated by the language model based on the follow-up prompt.
        """
        prompt = ActionItemsRefinePrompts.refine_prompt_default(follow_up)
        return self.llm.invoke(prompt)
    
    